project:
  type: website

website:
  title: "Josh Meehl"
  decription: "Josh Meehl's Data Science Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    analytics:
      google: G-TH229ZFG23



