project:
  type: website
  output-dir: docs

website:
  title: "Josh Meehl"
  description: "Josh Meehl's Data Science Portfolio"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Resume
        href: resume.qmd
      - text: Projects
        menu:
          - text: Protein Engineering
            href: projects/protein-engineering.qmd
          - text: Simulated Annealing
            href: projects/simulated-annealing.qmd
          - text: COVID Strain Clustering
            href: projects/covid-strain-clustering.qmd
          - text: MTG Analysis
            href: https://mage.meehl.org
      - text: Contact
        href: contact.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    analytics:
      google: G-TH229ZFG23



