project:
  type: website
  output-dir: docs

website:
  title: "Josh Meehl"
  description: "Josh Meehl's Data Science Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    analytics:
      google: G-TH229ZFG23



